#!/usr/bin/env php
<?php

class nicehashminer
{

	public $rig;
	public $config;
	public $stats;
	public $output;
	public $current;
	public $firstrun;
	public $best;

	public function __construct()
	{
		global $argv;
		$this->args = $argv;
		$this->rig = gethostname();
		$this->best = new stdClass();
		if(file_exists('config.json'))
		{
			$this->config = json_decode(file_get_contents('config.json'));
		}
		else
		{
			$this->output .="Missing a config.json file, please use the config.sample.json file as a template.\r\n";
			return;
		}
		$this->stats = $this->makerequest($this->config->settings->ethos_url, 1);
		$this->getprofitability();
		if($this->config->settings->dryrun == 0 && $this->config->settings->autoswitch == 1)
		{
			if($this->config->mine_duration==0 || ($this->config->mine_duration>0 && $this->stats->rigs->{$this->rig}->miner_secs/60 > $this->config->mine_duration*60))
			{
				$this->setconfig();
			}
		}
		if($this->config->settings->dryrun == 0 && $this->config->settings->gpuchecker == 1)
		{
			$this->rigcheck();
		}
		if($this->config->settings->dryrun == 1){
			$this->output.="This was a dry run\r\n";
		}
	}

	public function getprofitability()
	{
		$json = $this->makerequest($this->config->settings->nicehash_url, '', 1);
		if(!$json)
		{
			$this->output .="Unable to load JSON from Nicehash.\r\n";
			return;
		}
		$this->output .= "Summary: \r\n";
		foreach($json['result']['simplemultialgo'] as $id => $row)
		{
			if(array_key_exists($row['name'], $this->config->hashrates))
			{
				$profit = round($this->config->factors->$row['name'] * $row['paying'] * $this->config->hashrates->$row['name'], 8);
				$this->output .= $row['name'] . ":" . number_format($profit, 8) . "\r\n";
				if(!isset($this->best->profit) || (isset($this->best->profit) && $this->best->profit < $profit))
				{
					$this->best->name = $row['name'];
					$this->best->paying = $row['paying'];
					$this->best->profit = $profit;
				}
			}
		}
		$this->output .= "\r\nMost profitable coin is: " . $this->best->name . " at " . number_format($this->best->profit, 8) . "\r\n";
		$this->output .= "Miner uptime is: " . date('H:i:s', $this->stats->rigs->{$this->rig}->miner_secs) . "\r\n";
	}

	public function setcurrent()
	{
		$currentpool = explode(".", $this->stats->rigs->rig->$rig->pool);
		$this->current = $currentpool[0];
		if(!file_exists($this->config->settings->nicehashminer_dir . 'current.txt') || filesize($this->config->settings->nicehashminer_dir . 'current.txt') == 0)
		{
			file_put_contents($this->config->settings->nicehashminer_dir . 'current.txt', $this->current);
			$this->firstrun = true;
		}
		else
		{
			$this->current = file_get_contents($this->config->settings->nicehashminer_dir . 'current.txt');
		}
	}

	public function setconfig()
	{
		$this->setcurrent();
		if($this->current != $this->best->name || $this->firstrun == true)
		{
			if(empty($this->config->configs->$this->best->name))
			{
				$this->output .="Missing configuration for " . $this->best->name . ".\r\n";
				return;
			}
			if(file_exists($this->config->settings->nicehashminer_configs . $this->config->configs->$this->best->name))
			{
				copy($this->config->settings->nicehashminer_configs . $this->config->configs->$this->best->name, $this->config->settings->home_dir . 'local.conf');
				echo "Copied configuration from " . $this->config->settings->nicehashminer_configs . $this->config->configs->$this->best->name . ".\r\n";
			}
			else
			{
				$this->output .="Missing .conf file for " . $this->best->name . ".\r\n";
				return;
			}
			file_put_contents($this->config->settings->nicehashminer_dir . 'current.txt', $best['name']);

			$msg = 'Switching to ' . $this->best->name . ' for at least' . $this->stats->rigs->{$this->rig}->miner_secs . ' hour';
			$this->notify($msg);
		}
	}

	public function notify($msg)
	{
		if($this->config->settings->notify == 1 && !empty($this->config->settings->pushover->token) && !empty($this->config->settings->pushover->user))
		{
			$data = array(
				'token' => $this->config->settings->pushover->token,
				'user' => $this->config->settings->pushover->user,
				'title' => 'Nicehashminer',
				'message' => $msg,
			);
			$this->makerequest($config->settings->pushover->url, $data);
		}
	}

	public function rigcheck()
	{
		$hashfile = shell_exec('sudo tail -1 /var/run/ethos/miner_hashes.file');
		$hashes = explode(" ", $hashfile);
		foreach($hashes as $key => $value)
		{
			if($value < $this->config->minimumhash)
			{
				$gpudead = true;
			}
		}
		if(file_exists('gpufail.txt'))
		{
			$failcount = file_get_contents('gpufail.txt');
		}
		else
		{
			$failcount = 0;
		}
		if($gpudead > 0)
		{
			if($failcount > 5)
			{
				file_put_contents('0', 'gpufail.txt');
				$this->output .= "A GPU is failing: " . $hashfile . "\r\n";
				$msg = 'EthOS Rig ( ' . $this->rig . ' ) Rebooted.....' . $hashfile;
				$this->notify($msg);
				shell_exec('sudo reboot');
			}
			else
			{
				$this->output .= "A GPU is failing: " . $hashfile . "\r\n";
				$failcount++;
			}
		}
		else
		{
			$this->output .= "All GPUs are working: " . $hashfile . "\r\n";
			file_put_contents('0', 'gpufail.txt');
		}
	}

	public function makerequest($url, $data = "", $json = false)
	{
		$ch = curl_init();
		curl_setopt($ch, CURLOPT_URL, $url);
		curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 5);
		curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
		curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
		$result = curl_exec($ch);
		curl_close($ch);

		return json_decode($result, $json);
	}

}

$app = new nicehashminer();
echo $app->output;
